# Generated by Django 4.1 on 2022-09-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('gpd', models.CharField(max_length=3)),
            ],
        ),
    ]
