# Generated by Django 4.1 on 2022-09-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quota_request_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('subjects', models.ManyToManyField(to='quota_request_page.subject')),
            ],
        ),
    ]
