# Generated by Django 4.1 on 2022-09-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quota_request_page', '0002_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='n_steats',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
