# Generated by Django 4.1 on 2022-09-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quota_request_page', '0003_subject_n_steats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='gpd',
            field=models.CharField(default='0.0', max_length=3),
        ),
        migrations.AlterField(
            model_name='subject',
            name='n_steats',
            field=models.IntegerField(default=0),
        ),
    ]
