# Generated by Django 4.1 on 2022-09-09 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quota_request_page', '0004_alter_subject_gpd_alter_subject_n_steats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='n_steats',
            new_name='n_seats',
        ),
    ]
