# Generated by Django 4.1 on 2022-09-09 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quota_request_page', '0005_rename_n_steats_subject_n_seats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
