# Generated by Django 4.1 on 2022-09-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quota_request_page', '0006_rename_students_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='ocu_seats',
            field=models.IntegerField(default=0),
        ),
    ]
