# Generated by Django 4.1 on 2022-09-10 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quota_request_page', '0007_subject_ocu_seats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject_code',
            new_name='subject_id',
        ),
    ]
