# Generated by Django 4.1 on 2022-09-12 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='ocu_seats',
        ),
    ]
