# Generated by Django 4.1 on 2022-09-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0002_remove_subject_ocu_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='ocu_seats',
            field=models.IntegerField(default=0),
        ),
    ]
