# Generated by Django 4.1 on 2022-09-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0004_alter_subject_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='subjects',
        ),
        migrations.AddField(
            model_name='year',
            name='subjects',
            field=models.ManyToManyField(related_name='subjects', to='user_page.subject'),
        ),
    ]
