name: CI


on:push

jobs:
  test_project:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
  - name: Run Django unit tests
    run: 
      pip3 install --user -r requiremants.txt
      python3 manage.py makemigrations
      python3 manage.py migrate
      coverage run --source='.' manage.py test
      coverage report
